### ISSUE TITLE
"yo hubot" fails on ubuntu 14.04.

### ISSUE THREAD

**Issue by sylvesterjakubowski** [hubotio/hubot#1178]
/usr/lib/node_modules/yo/node_modules/yeoman-environment/node_modules/untildify/index.js:2
const osHomedir = require('os-homedir');
^^^^^
SyntaxError: Use of const in strict mode.
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/usr/lib/node_modules/yo/node_modules/yeoman-environment/lib/environment.js:10:17)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)

History:

   18  wget https://deb.nodesource.com/setup_dev
   19  chmod +x setup_dev 
   21  sudo ./setup_dev 
   22  sudo apt-get install nodejs
   25  sudo npm install -g yo generator-hubot
   27  mkdir hubot
   28  cd hubot/
   29  yo hubot

sjakubowski@sjakubowski-u:~/hubot$ uname -a
Linux sjakubowski-u 3.19.0-25-generic #26~14.04.1-Ubuntu SMP Fri Jul 24 21:16:20 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

Thanks.

**Comment by sylvesterjakubowski** [comment]
I managed to fix this by using 

https://deb.nodesource.com/setup_6.x

Instead, the documentation didn't seem to reference this.

**Comment by sylvesterjakubowski** [comment]
After updating npm / node:


sjakubowski@sjakubowski-u:~/hubot$ sudo yo hubot
                     _____________________________  
                    /                             \ 
   //\              |      Extracting input for    |
  ////\    _____    |   self-replication process   |
 //////\  /_____\   \                             / 
 ======= |[^_/\_]|   /----------------------------  
  |   | _|___@@__|__                                
  +===+/  ///     \_\                               
   | |_\ /// HUBOT/\\                             
   |___/\//      /  \\                            
         \      /   +---+                            
          \____/    |   |                            
           | //|    +===+                            
            \//      |xx|                            

? Owner Sylvester Jakubowski <sjakubowski@someemail.com>
? Bot name hubot
? Description A simple helpful robot for your Company
? Bot adapter (campfire) 


/usr/lib/node_modules/yo/node_modules/rx/dist/rx.js:77
    throw e;
    ^
true
sjakubowski@sjakubowski-u:~/hubot$ npm -version
3.8.8
sjakubowski@sjakubowski-u:~/hubot$ nodejs -v
v6.0.0

**Comment by sylvesterjakubowski** [comment]
I managed to fix this by running the 

`yo hubot --defaults
`
Command, which got futher,

It complained of:


`npm ERR! Refusing to install hubot as a dependency of itself
`

Which lead me to trying it from scratch in a new directory and it installed.

Hopefully this helps someone in the future.

**Comment by sylvesterjakubowski** [comment]
Another undocumented issue from 

https://hubot.github.com/docs/

When starting hubot got:

`sjakubowski@sjakubowski-u:~/hubot2/bin$ ./hubot 
./hubot: 8: exec: node_modules/.bin/hubot: not found
`


Resolved with:


`sudo npm install -g coffee-script`

**Comment by anoff** [comment]
same on ubuntu 15.10, node 5.10.0, npm 3.8.3
However coffeescript didn't fix it for me :( also get the `dependency of itself`error and `exec: node_modules/.bin/hubot: not found`
